CREATE TABLE AUDITORIA_INV 
( 
 id_auditoria INT NOT NULL AUTO_INCREMENT, 
 fecha_cambio DATE NOT NULL, 
 tipo_movimiento VARCHAR(25) NOT NULL, 
 cantidad_anterior INT NOT NULL, 
 cantidad_nueva INT NOT NULL, 
 motivo VARCHAR(100) NOT NULL, 
 USUARIO_rut INT NOT NULL, 
 INVENTARIO_id_inventario INT NOT NULL,
 PRIMARY KEY (id_auditoria)
);

CREATE TABLE AUTORIZACION
( 
 id_autorizacion INT NOT NULL AUTO_INCREMENT, 
 fecha_autorizacion DATE NOT NULL, 
 estado VARCHAR(25) NOT NULL, 
 comentario VARCHAR(100) NOT NULL, 
 USUARIO_rut INT NOT NULL, 
 SOLI_PRESTAMO_id_prestamo INT NOT NULL,
 PRIMARY KEY (id_autorizacion)
);

CREATE TABLE CATEGORIA_PROD 
( 
 id_categoria INT NOT NULL AUTO_INCREMENT, 
 nombre VARCHAR(25) NOT NULL,
 PRIMARY KEY (id_categoria)
);

CREATE TABLE DET_PRESTAMO 
( 
 id_detalle INT NOT NULL AUTO_INCREMENT, 
 cantidad INT NOT NULL, 
 fecha_incio_prestamo DATE NOT NULL, 
 fecha_retorno_prestamo DATE NOT NULL, 
 SOLI_PRESTAMO_id_prestamo INT NOT NULL, 
 PRODUCTO_id_principal INT NOT NULL, 
 fecha_devolucion_prestamo DATE,
 PRIMARY KEY (id_detalle)
);

CREATE TABLE DISPONIBILIDAD 
( 
 id_disp INT NOT NULL AUTO_INCREMENT, 
 nombre VARCHAR(25) NOT NULL,
 PRIMARY KEY (id_disp)
);

CREATE TABLE ESTADO 
( 
 id_estado INT NOT NULL AUTO_INCREMENT, 
 nombre VARCHAR(25) NOT NULL,
 PRIMARY KEY (id_estado)
);

CREATE TABLE IMAGEN 
( 
 id_imagen INT NOT NULL AUTO_INCREMENT, 
 url VARCHAR(500) NOT NULL,
 es_img_principal CHAR(1) NOT NULL, 
 PRODUCTO_id_principal INT NOT NULL,
 PRIMARY KEY (id_imagen),
 UNIQUE (url)
);

CREATE TABLE INVENTARIO 
( 
 id_inventario INT NOT NULL AUTO_INCREMENT, 
 observacion VARCHAR(100), 
 fecha_actualizacion DATE NOT NULL, 
 UBICACION_INV_id_ubicacion INT NOT NULL, 
 STOCK_id_stock INT NOT NULL,
 PRIMARY KEY (id_inventario)
);

CREATE TABLE MARCA 
( 
 id_marca INT NOT NULL AUTO_INCREMENT, 
 nombre VARCHAR(25) NOT NULL,
 PRIMARY KEY (id_marca)
);

CREATE TABLE PRODUCTO 
( 
 cod_interno BIGINT NOT NULL, 
 id_principal INT NOT NULL AUTO_INCREMENT, 
 estado VARCHAR(15) NOT NULL, 
 nombre_producto VARCHAR(25) NOT NULL, 
 marca VARCHAR(25), 
 INVENTARIO_id_inventario INT NOT NULL, 
 ESTADO_id_estado INT NOT NULL, 
 DISPONIBILIDAD_id_disp INT NOT NULL, 
 CATEGORIA_PROD_id_categoria INT NOT NULL, 
 MARCA_id_marca INT NOT NULL,
 PRIMARY KEY (id_principal),
 UNIQUE (cod_interno),
 CONSTRAINT OK_ESTADO CHECK (estado IN ('1'))
);

CREATE TABLE ROL 
( 
 id_rol CHAR(1) NOT NULL, 
 nombre_rol VARCHAR(25) NOT NULL,
 PRIMARY KEY (id_rol)
);

CREATE TABLE SOLI_PRESTAMO 
( 
 id_prestamo INT NOT NULL AUTO_INCREMENT, 
 estado_solicitud VARCHAR(15) NOT NULL, 
 USUARIO_rut INT NOT NULL, 
 fecha_solicitud DATE NOT NULL, 
 motivo_prestamo VARCHAR(100) NOT NULL, 
 prioridad VARCHAR(25) NOT NULL,
 PRIMARY KEY (id_prestamo),
 CONSTRAINT OK_ESTADO CHECK (estado_solicitud IN ('aprobado','pendiente'))
);

CREATE TABLE STOCK 
( 
 id_stock INT NOT NULL AUTO_INCREMENT, 
 stock_minimo INT NOT NULL, 
 stock_maximo INT NOT NULL, 
 cantidad INT NOT NULL,
 PRIMARY KEY (id_stock)
);

CREATE TABLE UBICACION_INV 
( 
 id_ubicacion INT NOT NULL AUTO_INCREMENT, 
 nombre_sala VARCHAR(50) NOT NULL, 
 estante VARCHAR(20) NOT NULL, 
 nivel INT NOT NULL, 
 descripcion VARCHAR(100),
 PRIMARY KEY (id_ubicacion)
);

CREATE TABLE USUARIO 
( 
 rut INT NOT NULL, 
 dv_rut CHAR(1) NOT NULL, 
 pnombre VARCHAR(25) NOT NULL, 
 snombre VARCHAR(25), 
 ap_paterno VARCHAR(25) NOT NULL, 
 ap_materno VARCHAR(25), 
 actividad CHAR(1) NOT NULL, 
 email VARCHAR(60) NOT NULL, 
 ROL_id_rol CHAR(1) NOT NULL,
 PRIMARY KEY (rut),
 UNIQUE (email),
 CONSTRAINT OK_DV_RUT CHECK (dv_rut IN ('0','1','2','3','4','5','6','7','8','9','K'))
);

ALTER TABLE AUDITORIA_INV 
 ADD CONSTRAINT AUDITORIA_INV_INVENTARIO_FK FOREIGN KEY (INVENTARIO_id_inventario) REFERENCES INVENTARIO(id_inventario);

ALTER TABLE AUDITORIA_INV 
 ADD CONSTRAINT AUDITORIA_INV_USUARIO_FK FOREIGN KEY (USUARIO_rut) REFERENCES USUARIO(rut);

ALTER TABLE AUTORIZACION 
 ADD CONSTRAINT AUTORIZACION_SOLI_PRESTAMO_FK FOREIGN KEY (SOLI_PRESTAMO_id_prestamo) REFERENCES SOLI_PRESTAMO(id_prestamo);

ALTER TABLE AUTORIZACION 
 ADD CONSTRAINT AUTORIZACION_USUARIO_FK FOREIGN KEY (USUARIO_rut) REFERENCES USUARIO(rut);

ALTER TABLE DET_PRESTAMO 
 ADD CONSTRAINT DET_PRESTAMO_PRODUCTO_FK FOREIGN KEY (PRODUCTO_id_principal) REFERENCES PRODUCTO(id_principal);

ALTER TABLE DET_PRESTAMO 
 ADD CONSTRAINT DET_PRESTAMO_SOLI_PRESTAMO_FK FOREIGN KEY (SOLI_PRESTAMO_id_prestamo) REFERENCES SOLI_PRESTAMO(id_prestamo);

ALTER TABLE IMAGEN 
 ADD CONSTRAINT IMAGEN_PRODUCTO_FK FOREIGN KEY (PRODUCTO_id_principal) REFERENCES PRODUCTO(id_principal);

ALTER TABLE INVENTARIO 
 ADD CONSTRAINT INVENTARIO_STOCK_FK FOREIGN KEY (STOCK_id_stock) REFERENCES STOCK(id_stock);

ALTER TABLE INVENTARIO 
 ADD CONSTRAINT INVENTARIO_UBICACION_INV_FK FOREIGN KEY (UBICACION_INV_id_ubicacion) REFERENCES UBICACION_INV(id_ubicacion);

ALTER TABLE PRODUCTO 
 ADD CONSTRAINT PRODUCTO_CATEGORIA_PROD_FK FOREIGN KEY (CATEGORIA_PROD_id_categoria) REFERENCES CATEGORIA_PROD(id_categoria);

ALTER TABLE PRODUCTO 
 ADD CONSTRAINT PRODUCTO_DISPONIBILIDAD_FK FOREIGN KEY (DISPONIBILIDAD_id_disp) REFERENCES DISPONIBILIDAD(id_disp);

ALTER TABLE PRODUCTO 
 ADD CONSTRAINT PRODUCTO_ESTADO_FK FOREIGN KEY (ESTADO_id_estado) REFERENCES ESTADO(id_estado);

ALTER TABLE PRODUCTO 
 ADD CONSTRAINT PRODUCTO_INVENTARIO_FK FOREIGN KEY (INVENTARIO_id_inventario) REFERENCES INVENTARIO(id_inventario);

ALTER TABLE PRODUCTO 
 ADD CONSTRAINT PRODUCTO_MARCA_FK FOREIGN KEY (MARCA_id_marca) REFERENCES MARCA(id_marca);

ALTER TABLE SOLI_PRESTAMO 
 ADD CONSTRAINT SOLI_PRESTAMO_USUARIO_FK FOREIGN KEY (USUARIO_rut) REFERENCES USUARIO(rut);

ALTER TABLE USUARIO 
 ADD CONSTRAINT USUARIO_ROL_FK FOREIGN KEY (ROL_id_rol) REFERENCES ROL(id_rol);
